services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
  mongo:
    image: mongo:latest
    container_name: mongo-latest
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=shortener
    volumes:
      - ./mongo-data:/data/db